### ISSUE TITLE
Error with python 3.6

### ISSUE THREAD

**Issue by pblankley** [singer-io/tap-facebook#108]
I install `tap-facebook` in a clean venv with python 3.6.8 and I get the following error running `tap-facebook --help`

```
Traceback (most recent call last):
  File "/blah/venv/bin/tap-facebook", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/blah/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3126, in <module>
    @_call_aside
  File "/blah/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3110, in _call_aside
    f(*args, **kwargs)
  File "/blah/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/blah/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/blah/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 596, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/blah/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 789, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (attrs 16.3.0 (/blah/venv/lib/python3.6/site-packages), Requirement.parse('attrs>=17.3.0'), {'aiohttp'})
```

This is my output of `pip freeze` 

```
aiohttp==3.6.2
async-timeout==3.0.1
attrs==16.3.0
backoff==1.8.0
certifi==2020.6.20
chardet==3.0.4
ciso8601==2.1.3
curlify==2.2.1
facebook-business==8.0.3
idna==2.7
idna-ssl==1.1.0
jsonschema==2.6.0
mock==4.0.2
multidict==4.7.6
pendulum==1.2.0
pycountry==20.7.3
python-dateutil==2.8.1
pytz==2018.4
pytzdata==2020.1
requests==2.20.0
simplejson==3.11.1
singer-python==5.8.1
six==1.15.0
tap-facebook==1.9.4
typing-extensions==3.7.4.3
tzlocal==2.1
urllib3==1.24.3
yarl==1.5.1
```

Any insight into this one?

**Comment by pblankley** [comment]
It seems to me that the error is due to not pinning the `aiohttp` dependency to a version that works with `attrs==16.3.0`

**Comment by maxlcoder** [comment]
Now, I install the `aiohttp==2.0.0` to avoid the conflict .
