### ISSUE TITLE
pkg_resources.ContextualVersionConflict: (attrs 16.3.0 (/home/geofflangenderfer/work/test_tap_facebook/.venv/lib/python3.8/site-packages), Requirement.parse('attrs>=17.3.0'), {'aiohttp'})

### ISSUE THREAD

**Issue by geofflangenderfer** [singer-io/tap-facebook#120]
```bash
(.venv)$ tap-facebook

Traceback (most recent call last):
  File "/home/geofflangenderfer/work/test_tap_facebook/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/geofflangenderfer/work/test_tap_facebook/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/geofflangenderfer/work/test_tap_facebook/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (attrs 20.3.0 (/home/geofflangenderfer/work/test_tap_facebook/.venv/lib/python3.8/site-packages), Requirement.parse('attrs==16.3.0'), {'tap-facebook'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/geofflangenderfer/work/test_tap_facebook/.venv/bin/tap-facebook", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/geofflangenderfer/work/test_tap_facebook/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/home/geofflangenderfer/work/test_tap_facebook/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/home/geofflangenderfer/work/test_tap_facebook/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/geofflangenderfer/work/test_tap_facebook/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/geofflangenderfer/work/test_tap_facebook/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/geofflangenderfer/work/test_tap_facebook/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'attrs==16.3.0' distribution was not found and is required by tap-facebook
```

**Comment by xtreding** [comment]
@geofflangenderfer try to:
1) delete aiohttp
2) upgrade pip
3) reinstall facebook tap
