### ISSUE TITLE
(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v5.0.

### ISSUE THREAD

**Issue by KobaKhit** [singer-io/tap-facebook#70]
I am trying to download data from one of the ad accounts and get this error. I tried cloning and updating `facebook_business` version to `5.0.1` and then reinstalling `tap-facebook`. It worked and that fixed the issue. Below is the original error. Let me know If I can provide more details.

```
tap-facebook -c config.json -p properties.json
```

```
ERROR 

  Message: Call was not successful
  Method:  GET
  Path:    https://graph.facebook.com/v4.0/me/adaccounts
  Params:  {'summary': 'true'}

  Status:  400
  Response:
    {
      "error": {
        "message": "(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v5.0.",
        "type": "OAuthException",
        "code": 2635,
        "fbtrace_id": "AXCdZoi0hBpoXGbHE3nXKXb"
      }
    }
Traceback (most recent call last):
  File "/Users/kobakhitalishvili/.local/share/virtualenvs/facebook_ads_api-DZzLcf3-/lib/python3.6/site-packages/tap_facebook/__init__.py", line 682, in main
    main_impl()
  File "/Users/kobakhitalishvili/.local/share/virtualenvs/facebook_ads_api-DZzLcf3-/lib/python3.6/site-packages/tap_facebook/__init__.py", line 663, in main_impl
    accounts = user.get_ad_accounts()
  File "/Users/kobakhitalishvili/.local/share/virtualenvs/facebook_ads_api-DZzLcf3-/lib/python3.6/site-packages/facebook_business/adobjects/user.py", line 537, in get_ad_accounts
    return request.execute()
  File "/Users/kobakhitalishvili/.local/share/virtualenvs/facebook_ads_api-DZzLcf3-/lib/python3.6/site-packages/facebook_business/api.py", line 663, in execute
    cursor.load_next_page()
  File "/Users/kobakhitalishvili/.local/share/virtualenvs/facebook_ads_api-DZzLcf3-/lib/python3.6/site-packages/facebook_business/api.py", line 830, in load_next_page
    params=self.params,
  File "/Users/kobakhitalishvili/.local/share/virtualenvs/facebook_ads_api-DZzLcf3-/lib/python3.6/site-packages/facebook_business/api.py", line 336, in call
    raise fb_response.error()
facebook_business.exceptions.FacebookRequestError: 

  Message: Call was not successful
  Method:  GET
  Path:    https://graph.facebook.com/v4.0/me/adaccounts
  Params:  {'summary': 'true'}

  Status:  400
  Response:
    {
      "error": {
        "message": "(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v5.0.",
        "type": "OAuthException",
        "code": 2635,
        "fbtrace_id": "AXCdZoi0hBpoXGbHE3nXKXb"
      }
    }

CRITICAL 
CRITICAL 
CRITICAL   Message: Call was not successful
CRITICAL   Method:  GET
CRITICAL   Path:    https://graph.facebook.com/v4.0/me/adaccounts
CRITICAL   Params:  {'summary': 'true'}
CRITICAL 
CRITICAL   Status:  400
CRITICAL   Response:
CRITICAL     {
CRITICAL       "error": {
CRITICAL         "message": "(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v5.0.",
CRITICAL         "type": "OAuthException",
CRITICAL         "code": 2635,
CRITICAL         "fbtrace_id": "AXCdZoi0hBpoXGbHE3nXKXb"
CRITICAL       }
CRITICAL     }
Traceback (most recent call last):
  File "/Users/kobakhitalishvili/.local/share/virtualenvs/facebook_ads_api-DZzLcf3-/bin/tap-facebook", line 8, in <module>
    sys.exit(main())
  File "/Users/kobakhitalishvili/.local/share/virtualenvs/facebook_ads_api-DZzLcf3-/lib/python3.6/site-packages/tap_facebook/__init__.py", line 690, in main
    raise e
  File "/Users/kobakhitalishvili/.local/share/virtualenvs/facebook_ads_api-DZzLcf3-/lib/python3.6/site-packages/tap_facebook/__init__.py", line 682, in main
    main_impl()
  File "/Users/kobakhitalishvili/.local/share/virtualenvs/facebook_ads_api-DZzLcf3-/lib/python3.6/site-packages/tap_facebook/__init__.py", line 663, in main_impl
    accounts = user.get_ad_accounts()
  File "/Users/kobakhitalishvili/.local/share/virtualenvs/facebook_ads_api-DZzLcf3-/lib/python3.6/site-packages/facebook_business/adobjects/user.py", line 537, in get_ad_accounts
    return request.execute()
  File "/Users/kobakhitalishvili/.local/share/virtualenvs/facebook_ads_api-DZzLcf3-/lib/python3.6/site-packages/facebook_business/api.py", line 663, in execute
    cursor.load_next_page()
  File "/Users/kobakhitalishvili/.local/share/virtualenvs/facebook_ads_api-DZzLcf3-/lib/python3.6/site-packages/facebook_business/api.py", line 830, in load_next_page
    params=self.params,
  File "/Users/kobakhitalishvili/.local/share/virtualenvs/facebook_ads_api-DZzLcf3-/lib/python3.6/site-packages/facebook_business/api.py", line 336, in call
    raise fb_response.error()
facebook_business.exceptions.FacebookRequestError: 

  Message: Call was not successful
  Method:  GET
  Path:    https://graph.facebook.com/v4.0/me/adaccounts
  Params:  {'summary': 'true'}

  Status:  400
  Response:
    {
      "error": {
        "message": "(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v5.0.",
        "type": "OAuthException",
        "code": 2635,
        "fbtrace_id": "AXCdZoi0hBpoXGbHE3nXKXb"
      }
    }
```

**Comment by KobaKhit** [comment]
I found the solution. As of 2019-11-11, `tap_facebook` uses `facebook_business==4.0.5` module as a dependency. You can upgrade/downgrade `facebook_business` module to match you facebook app's API version after installing `tap_facebook`. Alternatively, you may switch your facebook app's API version in the app's `Settings`.

You can set the app API version in `Settings > Advanced > Upgrade API Version`. Also, it is recommended to enable `Require App Secret` in the security section.
